

    # general:col.active_border = rgb(e0def4)
    # general:col.inactive_border = rgb(575279)

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    active_opacity = 0.85;
    inactive_opacity = 0.8;
    # rounding = 3
    rounding = 15

    blur {
        # enabled = false
        # enabled = false;
        size = 30
        passes = 2
        new_optimizations = true
        vibrancy_darkness = 0.4
        vibrancy = 0.3
        brightness = 0.9
        xray = false
    }

    # default
    shadow {
        enabled = true
        range = 30
        render_power = 2
        scale = 1.0

        color = rgba(00000055)
        offset = 0, 3

        # col.shadow = rgba(1a1a1aee)

    }

    glow {
        # enabled = yes        
    }
}
