# ===================================================
#
#         [ General/Appearance Configuation ]
#
# ===================================================
general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 4
    gaps_out = 8, 4, 4, 4
    border_size = 0



    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = true

    permission = /usr/bin/discord, screencopy, allow
}


animations {
    enabled = true

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    bezier = easeOut, 0,0,0,1

    bezier = bouncy, 0.65, 0, 0.35, 1
    bezier = easeInBack, 0.77, 0, 0.64, -0.31
    bezier = easeOutBack, 0.07, 1.36, 0.64, 0.97

    bezier = crispExit, 0.22, 0.61, 0.36, 1
    animation = border, 1, 10, crispExit
    animation = borderangle, 1, 10, crispExit

    animation = windowsIn, 1, 5, easeOutBack, popin 80%
    animation = windowsOut, 1, 4, easeOutBack, popin 90%
    animation = windowsMove, 1, 5, easeOutBack
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 5, default
    animation = workspacesIn, 1, 6, easeOutBack, slidefadevert 15%
    animation = workspacesOut, 1, 6, easeOutBack, slidefadevert 15%
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    disable_hyprland_logo = false
    col.splash = 0x665c54
    splash_font_family = JetBrains Mono
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    # vfr = true

    force_default_wallpaper = 0
}

xwayland {
  force_zero_scaling = true
}

monitor = , highres, auto, 2
