# Master switch for picking layout
general:layout = scrolling

# More on here : 
scrolling {
    column_width = 0.7
    fullscreen_on_one_column = true
    follow_focus = false
    focus_fit_method = 1
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = no # you probably want this
}